use domain::RankedChampionLane;

pub(crate) struct RankedChampionSeed {
    pub(crate) champion_id: i64,
    pub(crate) champion_name: &'static str,
    pub(crate) lane: RankedChampionLane,
    pub(crate) win_rate: f64,
    pub(crate) pick_rate: f64,
    pub(crate) ban_rate: f64,
    pub(crate) games: i64,
}

pub(crate) const RANKED_CHAMPION_SEEDS: &[RankedChampionSeed] = &[
    RankedChampionSeed {
        champion_id: 266,
        champion_name: "Aatrox",
        lane: RankedChampionLane::Top,
        win_rate: 50.8,
        pick_rate: 8.9,
        ban_rate: 12.4,
        games: 184_000,
    },
    RankedChampionSeed {
        champion_id: 122,
        champion_name: "Darius",
        lane: RankedChampionLane::Top,
        win_rate: 51.6,
        pick_rate: 7.2,
        ban_rate: 18.7,
        games: 152_000,
    },
    RankedChampionSeed {
        champion_id: 164,
        champion_name: "Camille",
        lane: RankedChampionLane::Top,
        win_rate: 50.2,
        pick_rate: 5.6,
        ban_rate: 9.8,
        games: 109_000,
    },
    RankedChampionSeed {
        champion_id: 114,
        champion_name: "Fiora",
        lane: RankedChampionLane::Top,
        win_rate: 49.9,
        pick_rate: 6.3,
        ban_rate: 14.6,
        games: 126_000,
    },
    RankedChampionSeed {
        champion_id: 86,
        champion_name: "Garen",
        lane: RankedChampionLane::Top,
        win_rate: 52.1,
        pick_rate: 6.8,
        ban_rate: 7.5,
        games: 139_000,
    },
    RankedChampionSeed {
        champion_id: 64,
        champion_name: "Lee Sin",
        lane: RankedChampionLane::Jungle,
        win_rate: 49.5,
        pick_rate: 14.9,
        ban_rate: 17.2,
        games: 276_000,
    },
    RankedChampionSeed {
        champion_id: 234,
        champion_name: "Viego",
        lane: RankedChampionLane::Jungle,
        win_rate: 50.7,
        pick_rate: 10.8,
        ban_rate: 13.9,
        games: 219_000,
    },
    RankedChampionSeed {
        champion_id: 59,
        champion_name: "Jarvan IV",
        lane: RankedChampionLane::Jungle,
        win_rate: 51.4,
        pick_rate: 8.1,
        ban_rate: 6.2,
        games: 168_000,
    },
    RankedChampionSeed {
        champion_id: 5,
        champion_name: "Xin Zhao",
        lane: RankedChampionLane::Jungle,
        win_rate: 52.3,
        pick_rate: 6.4,
        ban_rate: 5.8,
        games: 132_000,
    },
    RankedChampionSeed {
        champion_id: 131,
        champion_name: "Diana",
        lane: RankedChampionLane::Jungle,
        win_rate: 51.8,
        pick_rate: 5.9,
        ban_rate: 4.7,
        games: 118_000,
    },
    RankedChampionSeed {
        champion_id: 103,
        champion_name: "Ahri",
        lane: RankedChampionLane::Middle,
        win_rate: 51.1,
        pick_rate: 9.6,
        ban_rate: 8.3,
        games: 197_000,
    },
    RankedChampionSeed {
        champion_id: 134,
        champion_name: "Syndra",
        lane: RankedChampionLane::Middle,
        win_rate: 49.8,
        pick_rate: 7.8,
        ban_rate: 7.1,
        games: 158_000,
    },
    RankedChampionSeed {
        champion_id: 61,
        champion_name: "Orianna",
        lane: RankedChampionLane::Middle,
        win_rate: 50.6,
        pick_rate: 6.7,
        ban_rate: 3.2,
        games: 143_000,
    },
    RankedChampionSeed {
        champion_id: 777,
        champion_name: "Yone",
        lane: RankedChampionLane::Middle,
        win_rate: 49.4,
        pick_rate: 11.2,
        ban_rate: 24.5,
        games: 231_000,
    },
    RankedChampionSeed {
        champion_id: 517,
        champion_name: "Sylas",
        lane: RankedChampionLane::Middle,
        win_rate: 50.1,
        pick_rate: 8.4,
        ban_rate: 16.2,
        games: 176_000,
    },
    RankedChampionSeed {
        champion_id: 222,
        champion_name: "Jinx",
        lane: RankedChampionLane::Bottom,
        win_rate: 51.9,
        pick_rate: 12.6,
        ban_rate: 10.4,
        games: 248_000,
    },
    RankedChampionSeed {
        champion_id: 145,
        champion_name: "Kai'Sa",
        lane: RankedChampionLane::Bottom,
        win_rate: 50.4,
        pick_rate: 15.3,
        ban_rate: 11.8,
        games: 289_000,
    },
    RankedChampionSeed {
        champion_id: 81,
        champion_name: "Ezreal",
        lane: RankedChampionLane::Bottom,
        win_rate: 49.7,
        pick_rate: 18.1,
        ban_rate: 6.9,
        games: 321_000,
    },
    RankedChampionSeed {
        champion_id: 51,
        champion_name: "Caitlyn",
        lane: RankedChampionLane::Bottom,
        win_rate: 50.8,
        pick_rate: 10.7,
        ban_rate: 15.1,
        games: 213_000,
    },
    RankedChampionSeed {
        champion_id: 523,
        champion_name: "Aphelios",
        lane: RankedChampionLane::Bottom,
        win_rate: 48.9,
        pick_rate: 7.4,
        ban_rate: 4.3,
        games: 147_000,
    },
    RankedChampionSeed {
        champion_id: 412,
        champion_name: "Thresh",
        lane: RankedChampionLane::Support,
        win_rate: 50.5,
        pick_rate: 12.8,
        ban_rate: 9.6,
        games: 244_000,
    },
    RankedChampionSeed {
        champion_id: 117,
        champion_name: "Lulu",
        lane: RankedChampionLane::Support,
        win_rate: 51.3,
        pick_rate: 8.8,
        ban_rate: 12.9,
        games: 173_000,
    },
    RankedChampionSeed {
        champion_id: 111,
        champion_name: "Nautilus",
        lane: RankedChampionLane::Support,
        win_rate: 50.2,
        pick_rate: 10.5,
        ban_rate: 18.2,
        games: 206_000,
    },
    RankedChampionSeed {
        champion_id: 497,
        champion_name: "Rakan",
        lane: RankedChampionLane::Support,
        win_rate: 52.0,
        pick_rate: 7.9,
        ban_rate: 5.9,
        games: 151_000,
    },
    RankedChampionSeed {
        champion_id: 89,
        champion_name: "Leona",
        lane: RankedChampionLane::Support,
        win_rate: 51.7,
        pick_rate: 7.1,
        ban_rate: 6.8,
        games: 138_000,
    },
];
